### ISSUE TITLE
.graphql file isn't being detected

### ISSUE THREAD

**Issue by LetrixZ** [AniTrend/retrofit-graphql#119]
I followed the [Getting Started](https://github.com/AniTrend/retrofit-graphql/wiki/Getting-Started) guide to try this but the only way to get a response is to pass a QueryContainer reading the .graphql file instead of passing the builder with the @GraphQuery annotation

I checked the demo app and it's done the 'same' way the guide says. Tried moving GetMarketplaceListing.graphql to another dir and still worked. Renaming the file made stopped working.

This was tested on AVD API 30 and on a Redmi Note 5 Android 10.

**NOT Working**
MainActivity:
```
val query = QueryContainerBuilder().putVariable("idMal", 40060)
val anime = apiService.get(query)
```
ApiService (interface):
```
@POST("/graphql")
@GraphQuery("GetAnime")
suspend fun get(@Body builder: QueryContainerBuilder): Response<GraphContainer<Data>>
```

Body is null and the errorBody is 'Must provide query string'

**Working**
MainActivity:
```
val query = QueryContainerBuilder().setQuery(assets.open("graphql/queries/GetAnime.graphql").bufferedReader().readText())
.putVariable("idMal", 40060).build()
val anime = apiService.get(query)
```
ApiService (interface):
```
@POST("/graphql")
suspend fun get(@Body builder: QueryContainer): Response<GraphContainer<Data>>
```

This way the request is done fine and I get the data that I want.

GetAnime.graphql
```
query GetAnime($idMal: Int) {
    anime(idMal: $idMal) {
        id
        idMal
        idAl
    }
}
```

**Comment by wax911** [comment]
Hi, are you sure that the `.graphql` file isn't being detected? Can you check the logcat as you make the request you should find the following output:
```sh
"The requested query annotated with value: `GetAnime` could not be found!"
```
If the file isn't found

**Comment by LetrixZ** [comment]
I wasn't getting any output, so I added this to my Retrofit contructor:
```
addConverterFactory(GraphConverter(GraphProcessor(AssetManagerDiscoveryPlugin(assetManager = context.assets),logger = DefaultGraphLogger(ILogger.Level.VERBOSE)), Gson()))
```

Output:
```
V/GraphProcessor: main: has obtained a synchronized lock on the object
V/GraphProcessor: main: is initializing query files
W/AssetManagerDiscoveryPlugin: Assets do not contain any files/folders in the path -> graphql
V/GraphProcessor: main: has completed initializing all graphql files
V/GraphProcessor: main: discovered `0` graphql files
```

Running this I can get the first line of the file:
```
assets.open("GetAnime.graphql").bufferedReader().readLine()
```

**Comment by LetrixZ** [comment]
I'm trying on another project and the same issue. This is all the logging I have and I only receive only those 4 lines from GraphProcessor.
`MainActivity$onCreate` is where I called it using `CoroutineScope(Dispatchers.IO).launch`
[logcat.txt](https://github.com/AniTrend/retrofit-graphql/files/6236441/logcat.txt)

**Comment by wax911** [comment]
Just out of curiosity, what does your assets folder structure look like?

**Comment by LetrixZ** [comment]
This is the project I'm working it right now: https://github.com/LetrixZ/miranime
[assets folder](https://github.com/LetrixZ/miranime/tree/main/app/src/main/assets)
[ApiService Interface](https://github.com/LetrixZ/miranime/blob/main/app/src/main/java/com/letrix/miranime/data/network/ApiService.kt)
[Retrofit Builder](https://github.com/LetrixZ/miranime/blob/main/app/src/main/java/com/letrix/miranime/di/RetrofitModule.kt)

**Comment by wax911** [comment]
I think I found your problem, in `provideApiService`
```kotlin
    .addConverterFactory(GraphConverter.create(context, ILogger.Level.VERBOSE))
    .addConverterFactory(GsonConverterFactory.create(GsonBuilder().create()))
```
Swap the order of graph converter and gson converter, otherwise retrofit will default to the Gson and you should see more loggs
```sh
2021-04-01 12:02:32.146 9534-9534/com.letrix.miranime V/GraphProcessor: main: has obtained a synchronized lock on the object
2021-04-01 12:02:32.146 9534-9534/com.letrix.miranime V/GraphProcessor: main: is initializing query files
2021-04-01 12:02:32.154 9534-9534/com.letrix.miranime V/GraphProcessor: main: has completed initializing all graphql files
2021-04-01 12:02:32.154 9534-9534/com.letrix.miranime V/GraphProcessor: main: discovered `3` graphql files
2021-04-01 12:02:32.250 9534-9569/com.letrix.miranime D/GraphProcessor: Looking up `.graphql` file matching: GetHome.graphql
```

> **N.B** `GraphConverter` has factory methods to initialise everything you need e.g. `GraphConverter.create(context, ILogger.Level.VERBOSE)`

**Comment by LetrixZ** [comment]
It worked! Thanks :)
