### ISSUE TITLE
Automated Persisted Queries

### ISSUE THREAD

**Issue by rrva** [AniTrend/retrofit-graphql#3]
Transparent support for Automated Persisted Queries (APQ) would be very useful. It makes queries smaller by sending a query id instead of the full query body, since there might be a size limit on HTTP POST bodies, or might cause performance problems when the body is large. It also allows clients to use HTTP GET instead of HTTP POST, making it easier to cache in a CDN (which might not allow caching of HTTP POST). The automated part is that the protocol allows clients to register new query id:s on the fly, so they do not have to be known by the server beforehand.

The protocol is simple:

1. The client optimistically sends a query id instead of the query which is a sha256 hash of the query body. 
2. If the query id is not previously known by the server, the server sends a graphql error response with a PersistedQueryNotFound message
3. The client then sends the full query body using HTTP POST, which the server then registers for future use

The full story is here: https://blog.apollographql.com/improve-graphql-performance-with-automatic-persisted-queries-c31d27b8e6ea

And the exact protocol is here:

https://github.com/apollographql/apollo-link-persisted-queries

This would be great if this was easy to enable by some configuration.

**Comment by rrva** [comment]
Any news on this? We are trying to implement this ourselves, not sure yet how it will fit together with retrofit. Retrofit Call Adapters turned out to be a bit of a cumbersome route, since we essentially want to convert all initial POST requests to GET requests with hashed id instead of query. If that GET request fails, we want to re-issue the original POST request

**Comment by Krillsson** [comment]
hi @wax911. I'm from the same organisation as @rrva. We have implemented a solution for persisted queries and will be submitting a PR for your reviewal shortly.
