### ISSUE TITLE
File Uploading

### ISSUE THREAD

**Issue by umeshkanhasoft** [AniTrend/retrofit-graphql#58]
how to work when i use multipart file uploading is thire any idea.

**Comment by wax911** [comment]
Hi @umeshkanhasoft sorry for the late reply, not sure how I missed this issue. Do you still need help figuring out how to upload files?

**Comment by umeshkanhasoft** [comment]
Thanks for the replay, I really need to know how file uploading work throw GraphQl. Actually I have used GraphQl structure in my real project and for that I have to integrate file uploading logic.

If you are going to give me any reference that is really great help me.

**Comment by wax911** [comment]
Please note that I personally haven't done any file uploads using graphql. But depending on your chosen graphql sever.

You will have to implement the requirements into a [request converter](https://github.com/AniTrend/retrofit-graphql/blob/master/app/src/main/java/io/github/wax911/retgraph/api/retro/converter/request/RequestConverter.kt) as demonstrated in the sample application. I will assume you already know about retrofit and how to customise add request converters using annotations to your benefit.

**Comment by arifmc** [comment]
Hello,  maybe you can provide some example for this case? your help is very appreciated @wax911 .

Thank you

**Comment by sbattaglino** [comment]
Hello! Any working example of this? I'm not sure how to extend the converter in order to work with multipart. I have an example working, but I'm sending the query hard coded and works.


@Multipart
@POST("/graphql")
@GraphQuery("CreateIncident")
suspend fun createIncident(
    @Header("Authorization") header: String,
    @Part operations: MultipartBody.Part,
    @Part map: MultipartBody.Part,
    @Part incidentImage: MultipartBody.Part
): NetworkResponse<GraphContainer<IncidentResponse>, ErrorResponse>

        //val requestBody = QueryContainerBuilder()
        //requestBody.putVariable("variables", CreateIncidentRequest())

        // TODO find a way to build the query as multipart form data
        val operationsPart = MultipartBody.Part.createFormData(
            "operations",
            "{\"query\":\"mutation CreateIncident(\$input:CreateIncidentInput!, \$photo: Upload!) {\\n  createIncident (input: \$input, photo: \$photo) {\\n    id\\n    title\\n    description\\n    latitude\\n    longitude\\n  address photo\\n thumbnail\\n userCreate {\\n      id\\n      email\\n    }\\n  }\\n}\\n\\n\",\"variables\":{\"input\":{\"title\":\"Test title\",\"description\":\"Incident description\",\"longitude\":25.66,\"latitude\":11.44, \"address\":\"My Address is Juncal 3706\", \"thumbnailSize\":{\"width\":800,\"height\":600}}}}"
        )

        val mapPart = MultipartBody.Part.createFormData(
            "map",
            "{\"incidentImage\": [\"variables.photo\"]}"
        )

        val incidentImagePart = MultipartBody.Part.createFormData(
            "incidentImage",
            file.name,
            file.asRequestBody("image/*".toMediaTypeOrNull())
        )

        return when (val networkResponse =
            api.createIncident(token, operationsPart, mapPart, incidentImagePart)) {
            is NetworkResponse.Success -> {
                val incident = networkResponse.body.data?.incident
                incident?.let {
                    saveIncidentLocal(it)
                }
                ResultIncident(incident, null)
            }
            is NetworkResponse.ServerError -> {
                Log.d(
                    tag,
                    ErrorObject(networkResponse.code, networkResponse.body?.message).toString()
                )
                ResultIncident(
                    null,
                    ErrorObject(networkResponse.code, networkResponse.body?.message)
                )
            }
            is NetworkResponse.NetworkError -> {
                Log.e(tag, ErrorObject(0, networkResponse.error.message).toString())
                ResultIncident(null, null)
            }
        }

**Comment by wax911** [comment]
Hi @sbattaglino thanks for the working example, I need to find a new sample graphql endpoint to test with, alternatively I might have to make a local example and see if I can make a sample with multipart converter

**Comment by wax911** [comment]
Hey everyone sorry for the long wait, I've been busy as of late but finally got around this. As you've probably seen I've referenced this issue in multiple commits regarding file uploads, please check them out and the newly re-written sample app which you can setup using the [wiki instructions](https://github.com/AniTrend/retrofit-graphql/wiki)

**Comment by wax911** [comment]
I'm going to close this issue for now, if you ever have any additional issue or suggestions regarding this please feel free to re-open it :+1:
