### ISSUE TITLE
Filtering of the log messages does not work

### ISSUE THREAD

**Issue by Cilenco** [AniTrend/retrofit-graphql#59]
In response to the pull request #53:

## Description Of Bug
The log messages are not filtered as expected when setting the [Logger](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt) level.

## Solution
The if statements of the form `if(level < LogLevel.XXX)` in the [Logger](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt) object have to be swapped to `if(level > LogLevel.XXX)`. The affected lines are [49](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L49), [61](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L61), [73](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L73), [85](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L85), [97](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L97) and [109](https://github.com/AniTrend/retrofit-graphql/blob/develop/library/src/main/java/io/github/wax911/library/util/Logger.kt#L109). Would you like me to open a pull request again or will you change the lines yourself?

**Comment by wax911** [comment]
Thank you for the report @Cilenco you're more than welcome to open a PR :heart: would be highly appreciated
