### ISSUE TITLE
Request to change license to a more permissive one

### ISSUE THREAD

**Issue by Krillsson** [AniTrend/retrofit-graphql#6]
This project appears to be using the [*GNU General Public License v3.0*](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)). This license is regarded infectious; any code that uses a GPL library automatically becomes GPL as well. Meaning any users of this library also need to disclose the source code of their application to the general public. A total dealbreaker for most commercial project.

Would it be possible to change the license to a more permissive one like [Apache-2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))?

**Comment by wax911** [comment]
That would not be an issue, thank you for the suggestion!
