### ISSUE TITLE
Support Android libraries

### ISSUE THREAD

**Issue by john-sardinha-pbx** [AniTrend/retrofit-graphql#71]
Currently the library requires the GraphQL queries to be on the /assets folder, but the /assets folder [can only be packaged into an apk, not an aar.](https://developer.android.com/studio/projects#ProjectView) Would be cool if there was a way to keep the GraphQL queries in maybe /res, so an Android library can also use this library.

**Comment by wax911** [comment]
Thanks for the suggestion, will see what I can do

**Comment by wax911** [comment]
Hi @john-sardinha-pbx I've referenced this issue on several commits all leading to 2 possible ways to extend the functionality of the processor, please check them out and the newly re-written sample app which you can find instructions on how to build from the [wiki](https://github.com/AniTrend/retrofit-graphql/wiki)
