### ISSUE TITLE
Dynamic Selection Set at Runtime

### ISSUE THREAD

**Issue by MatthewPatience** [AniTrend/retrofit-graphql#73]
## Question
Is there a way to modify the selection set of a query at runtime. I have a query where I have many possible selection sets based upon user input. I'm hoping to only have one query file for all of the iterations because it's a complicated query and only a small portion of the selection set gets modified.

I also wouldn't mind if there is a way to manually create the query via strings. I notice that QueryContainerBuilder has a setQuery function which would work, but after reading the code it seems that this function is actually an internal function that gets overriden?

Thanks!

**Comment by wax911** [comment]
Hi @MatthewPatience not entirely sure that I follow the first section of your question regarding dynamically modifying query at runtime based on user input. However the second option should be possible by creating your own custom request converter such as the one found in the sample app: [`io.github.wax911.retgraph.api.retro.converter.request`](https://github.com/AniTrend/retrofit-graphql/tree/master/app/src/main/java/io/github/wax911/retgraph/api/retro/converter/request) and ommit `.setQuery` on the `QueryContainerBuilder`: 

![image](https://user-images.githubusercontent.com/7859175/75763679-4af63f00-5d45-11ea-9ccb-e0438dffdf5f.png)

> The above implementation sets the query at runtime using the annotated retrofit query name specified in the `GraphQuery` annotation on the retrofit interface method, which prevents any queries set in `QueryContainerBuilder` from being overwritten in a scenario where you might have the following: 

![image](https://user-images.githubusercontent.com/7859175/75764936-4d599880-5d47-11ea-959b-bb9197c13933.png)

**Comment by MatthewPatience** [comment]
Thanks @wax911, much appreciated! Exactly what I was looking for.
